channels:
  - conda-forge
  - bioconda
dependencies:
  #Python
  - numpy
  - matplotlib
  - pandas
  - rpy2
  - session-info
  - seaborn
  - cartopy
  - rapidfuzz
  # R
  - r-base=3.6.2
  - r-tidyverse
  - r-raster
  - r-gdalutils
  - r-data.table
  - r-bit64
  - bioconductor-pcamethods
