channels:
  - conda-forge
  - bioconda
dependencies:
  #R
  - r-base=3.6
  - r-tidyverse
  - r-raster
  - bioconductor-pcamethods
  #Python
  - numpy
  - matplotlib
  - pandas
  - rpy2
  - session-info
  - seaborn
  - cartopy
  - rapidfuzz
